name: Dependency Review

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    strategy:
      matrix:
        go-version: ["1.22"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
      - name: Dependency Review
        uses: actions/dependency-review-action@0659a74c94536054bfa5aeb92241f70d680cc78e