name: Code Linting

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Code Linting
    strategy:
      matrix:
        go-version: ["1.22"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 1

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version: ${{ matrix.go-version }}
      id: go
      
    - name: Restore Go cache
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum', 'testdata/**') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8